name: Build App CI

on:
    pull_request:
        branches: ['develop']

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:            
            - name: Check App BoraRachar!
              uses: actions/checkout@v4
              
            - name: Login in DockerHub
              uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
              with:
                  username: ${{ secrets.Docker_User }}
                  password: ${{ secrets.Docker_Pass }}
            
            - name: Get metadata(tag, label)
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: luisroxis/boraracharapi
            
            - name: Build and push App BoraRachar!
              id: push
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ../../src/BoraRachar.Api/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
            
            - name: Gerar Pacote
              uses: actions/attest-build-provenance@v1
              with:
                  subject-name: luisroxis/boraracharapi
                  subject-digest: ${{ steps.push.outputs.digest }}
                  push-to-regsitry: true            
            
        
